import type { AssessmentAreaConfig } from '../types/assessment';

export const ASSESSMENT_AREAS: AssessmentAreaConfig[] = [
  {
    id: 1,
    name: 'Vision, Goals & Ownership',
    description: 'Clarity of vision, goal-setting, and ownership structure.',
    questionNew: 'Describe your current vision, main goals, and how ownership/decision-making is structured.',
    questionEstablished: 'How clearly defined are your vision, strategic goals, and ownership structure today?',
    futureVisionQuestion: 'Outline your ideal vision, goals, and ownership model for the next 3 years.',
    establishedOnly: false,
  },
  {
    id: 2,
    name: 'Customers & Value Proposition',
    description: 'Customer understanding and value proposition.',
    questionNew: 'Who are your target customers and what value do you offer them today?',
    questionEstablished: 'How well do you understand your customers and how differentiated is your value proposition?',
    futureVisionQuestion: 'Describe your ideal customer base and value proposition in 3 years.',
    establishedOnly: false,
  },
  {
    id: 3,
    name: 'External Environment',
    description: 'Market trends, competitors, and regulatory factors.',
    questionNew: 'What market trends, competitors, or regulatory factors affect your business today?',
    questionEstablished: 'Analyze market trends, competitor movements, and regulatory shifts affecting your business.',
    futureVisionQuestion: 'How do you want to position against market and regulatory changes in 3 years?',
    establishedOnly: false,
  },
  {
    id: 4,
    name: 'Contracts, Laws & IP',
    description: 'Legal, contractual, and IP maturity.',
    questionNew: 'Describe your current approach to contracts, compliance, and intellectual property.',
    questionEstablished: 'How mature are your contracts, legal compliance, and IP protection?',
    futureVisionQuestion: 'Outline your target legal, contractual, and IP setup for the next 3 years.',
    establishedOnly: false,
  },
  {
    id: 5,
    name: 'Sales & Marketing',
    description: 'Sales and marketing capability.',
    questionNew: 'How do you currently reach customers and what sales/marketing efforts are in place?',
    questionEstablished: 'How effective are your sales and marketing channels and messaging?',
    futureVisionQuestion: 'Describe your ideal sales and marketing engine in 3 years.',
    establishedOnly: false,
  },
  {
    id: 6,
    name: 'Economy & Financing',
    description: 'Financial health and funding.',
    questionNew: 'What is your current financial situation and funding approach?',
    questionEstablished: 'How healthy is your economics and financing, and what are your funding options?',
    futureVisionQuestion: 'What financial structure and funding do you aim for in 3 years?',
    establishedOnly: false,
  },
  {
    id: 7,
    name: 'Production & Service Delivery',
    description: 'Operations and delivery capability.',
    questionNew: 'How do you currently produce or deliver your product or service?',
    questionEstablished: 'How scalable and efficient is your production and service delivery?',
    futureVisionQuestion: 'Describe your target production and delivery model in 3 years.',
    establishedOnly: false,
  },
  {
    id: 8,
    name: 'Team & Resources',
    description: 'Team and resource adequacy.',
    questionNew: 'Describe your current team size, skills, and key resources.',
    questionEstablished: 'How adequate are your team and resources for your growth plans?',
    futureVisionQuestion: 'Outline your ideal team and resource setup for the next 3 years.',
    establishedOnly: false,
  },
  {
    id: 9,
    name: 'Leadership',
    description: 'Leadership capability and governance.',
    questionNew: 'Describe your current leadership structure and key decision-makers.',
    questionEstablished: 'How strong is your leadership and governance for scaling?',
    futureVisionQuestion: 'What leadership and governance do you want in place in 3 years?',
    establishedOnly: true,
  },
  {
    id: 10,
    name: 'Sustainability',
    description: 'Environmental and social sustainability.',
    questionNew: 'What sustainability considerations matter to your business today?',
    questionEstablished: 'How integrated are sustainability practices into your operations and strategy?',
    futureVisionQuestion: 'What sustainability goals do you want to achieve in 3 years?',
    establishedOnly: false,
  },
  {
    id: 11,
    name: 'Technology',
    description: 'Technology stack and digital capability.',
    questionNew: 'What technology do you use today and what are your main tech constraints?',
    questionEstablished: 'How modern and scalable is your technology stack and digital capability?',
    futureVisionQuestion: 'Describe your target technology and digital setup in 3 years.',
    establishedOnly: false,
  },
];

export const TOTAL_STEPS = 11;
export const MAX_CURRENT_STATE_CHARS = 1000;
export const MAX_FUTURE_VISION_CHARS = 500;
